
var AllBooks = {'books':[
  {'id':'ISBN001','name':'My experiments with Truth','author':'Mahatma M.K.Gandhi','desc':'The Story of My Experiments with Truth is the autobiography of Mohandas K. Gandhi, covering his life from early childhood through to 1921. It was written in weekly instalments and published in his journal Navjivan from 1925 to 1929. Its English translation also appeared in installments in his other journal Young India.[1] It was initiated at the insistence of Swami Anand and other close co-workers of Gandhi, who encouraged him to explain the background of his public campaigns. In 1999, the book was designated as one of the "100 Best Spiritual Books of the 20th Century" by a committee of global spiritual and religious authorities.','available':true},
  {'id':'ISBN002','name':'Far from the Madding Crowd','author':'Thomas Hardy','desc':'Bathsheba must deal with trials and tribulations of life while dealing with the attention of three men, a sheep farmer, a reckless sergeant and a well-to-do, mature bachelor.','available':true},
  {'id':'ISBN003','name':'Geetanjali','author':'Rabindra Nath Tagore','desc':'Gitanjali is a collection of poems by the Bengali poet Rabindranath Tagore. The original Bengali collection of 157 poems was published on August 14, 1910.','available':true},
  {'id':'ISBN004','name':'One Day in the Life of Ivan Denisovitch','author':'Alexander Solzhenitsyn','desc':'Plot. Ivan Denisovich Shukhov has been sentenced to a camp in the Soviet gulag system. He was accused of becoming a spy after being captured by the Germans as a prisoner of war during World War II. He is innocent, but is sentenced to ten years in a forced labor camp.','available':true},
  {'id':'ISBN005','name':'The Merchant of venice','author':'William shakespeare','desc':'The Merchant of Venice is a 16th century play by William Shakespeare in which a merchant in Venice must default on a large loan provided by an abused Jewish moneylender. It is believed to have been written between 1596 and 1599.','available':true},
  {'id':'ISBN006','name':'The Moon and Six pense','author':'Somerset Maughan','desc':'The Moon and Sixpence. Based on the life of Paul Gauguin, The Moon and Sixpence is W. Somerset Maugham`s ode to the powerful forces behind creative genius. Charles Strickland is a staid banker, a man of wealth and privilege. He is also a man possessed of an unquenchable desire to create art.','available':true},
  {'id':'ISBN007','name':'Anand Math','author':'Bankimchandra Chattopadhyay','desc':'by Bankim Chandra Chatterjee and published in 1882. Set in the background of the Sannyasi Rebellion in the late 18th century, it is considered one of the most important novels in the history of Bengali and Indian literature.[1] Its importance is heightened by the fact that it became synonymous with the struggle for Indian independence from the British Empire. The novel was banned by the British. The ban was lifted later by the Government of India after independence.','available':true},
  {'id':'ISBN008','name':'A Tale of Two Cities','author':'Charles Dickens','desc':'A Tale of Two Cities, which is one of two historical novels written by Charles Dickens, is set in London and in Paris and the French countryside at the time of the French Revolution. The book is sympathetic to the overthrow of the French aristocracy but highly critical of the reign of terror that followed.','available':true},
  {'id':'ISBN009','name':'Utopia','author':'Sir Thomas Moor','desc':'is a work of fiction and political philosophy by Thomas More (1478–1535) published in 1516 in Latin. The book is a frame narrative primarily depicting a fictional island society and its religious, social and political customs. Many aspects of More`s description of Utopia are reminiscent of life in monasteries.','available':true},
  {'id':'ISBN010','name':'Origin of species','author':'Charles Darwin','desc':'On the Origin of Species (or more completely, On the Origin of Species by Means of Natural Selection, or the Preservation of Favoured Races in the Struggle for Life), published on 24 November 1859, is a work of scientific literature by Charles Darwin which is considered to be the foundation of evolutionary biology.','available':true},
  {'id':'ISBN011','name':'David Copperfield','author':'Charles Dickens','desc':'David Copperfield He is the central character in the novel and tells the story of his life from birth to adulthood. ... Peggotty marries Barkis, the cart-driver, and continues throughout the novel to be David`s friend. Edward Murdstone David`s stepfather.','available':true},
  {'id':'ISBN012','name':'A passage to India','author':'E.M.Forster','desc':'A Passage to India (1924) is a novel by English author E. M. Forster set against the backdrop of the British Raj and the Indian independence movement in the 1920s.','available':true},
  {'id':'ISBN013','name':'Gulliver`s Travels','author':'Jonathan Swift','desc':'By Lemuel Gulliver, First a Surgeon, and then a Captain of Several Ships, (1726, amended 1735), is a prose satire by Irish writer and clergyman Jonathan Swift, that is both a satire on human nature and the travellers tales literary subgenre.','available':true},
  {'id':'ISBN014','name':'Discovery of India','author':'Pandit Jawaharlal Nehru','desc':'The Discovery of India. The Discovery of India was written by India`s first Prime Minister Jawaharlal Nehru during his imprisonment in 1942–46 at Ahmednagar fort in Maharashtra, India.','available':true},
  {'id':'ISBN015','name':'The Vicar of Wakefield','author':'Oliver Goldsmith','desc':'The Vicar of Wakefield. The Vicar of Wakefield – subtitled A Tale, Supposed to be written by Himself – is a novel by Irish writer Oliver Goldsmith (1728–1774). ... It was one of the most popular and widely read 18th-century novels among Victorians.','available':true},
  {'id':'ISBN016','name':'The fall of the Roman Empire','desc':'For the historical events, see History of the Roman Empire and Fall of the Western Roman Empire. For the historiography spawned by Gibbon`s theories, see Historiography of the fall of the Western Roman Empire. For publication details and chapter listings, see Outline of The History of the Decline and Fall of the Roman Empire.','author':'	Edward Gibbon','desc':'','available':true},
  {'id':'ISBN017','name':'The Lady of the Last Minstrel','author':'Sir Walter Scott','desc':'Scott had spent considerable time in compiling a collection of traditional ballads. He began The Lay of the Last Minstrel in 1802 and intended it as part of The Minstrelsy of the Scottish Border. Scott was kicked by a horse, while on maneuvers with his cavalry regiment. He worked on the first Canto while recuperating. When the Countess of Dalkeith suggested he include the local legend of the goblin Gilpin Horner in his original tale of Border rivalries, he realized it would be too long for The Minstrelsy, and decided to publish it as a separate work. It was eventually finished in 1804 and published in early 1805.','available':true},
  {'id':'ISBN018','name':'Pride and Prejudice','author':'Jane Austen','desc':'Pride and Prejudice is a humorous story of love and life among English gentility during the Georgian era. Mr Bennet is an English gentleman living in Hartfordshire with his overbearing wife. The Bennets 5 daughters; the beautiful Jane, the clever Elizabeth, the bookish Mary, the immature Kitty and the wild Lydia.','available':true},
  {'id':'ISBN019','name':'Time Machine','author':'H.G. Wells','desc':'The Time Machine is a science fiction novel by H. G. Wells, published in 1895 and written as a frame narrative. Wells is generally credited with the popularization of the concept of time travel by using a vehicle that allows an operator to travel purposely and selectively forwards or backwards in time. The term "time machine", coined by Wells, is now almost universally used to refer to such a vehicle.','available':true},
  {'id':'ISBN020','name':'Arthashastra','author':'Kautilya','desc':'The Arthashastra explores issues of social welfare, the collective ethics that hold a society together, advising the king that in times and in areas devastated by famine, epidemic and such acts of nature, or by war, he should initiate public projects such as creating irrigation waterways and building forts around major strategic holdings and towns and exempt taxes on those affected.[20] The text was influential on other Hindu texts that followed, such as the sections on king, governance and legal procedures included in Manusmriti.','available':true}
]};

export default AllBooks
